package view;

import com.microsoft.sqlserver.jdbc.SQLServerException;
import controller.Dao_Departamento;
import controller.Dao_Funcionario;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Departamento;
import model.Funcionario;

public class CadastroFuncionario extends javax.swing.JInternalFrame {

    //metodo para ajustar a tabela
    public void ajustarTabela() {
        TabelaFuncionario.getColumnModel().getColumn(0).setPreferredWidth(50);
        TabelaFuncionario.getColumnModel().getColumn(1).setPreferredWidth(200);
        TabelaFuncionario.getColumnModel().getColumn(2).setPreferredWidth(50);
        TabelaFuncionario.getColumnModel().getColumn(3).setPreferredWidth(100);
        TabelaFuncionario.getColumnModel().getColumn(4).setPreferredWidth(50);
        TabelaFuncionario.getColumnModel().getColumn(5).setPreferredWidth(200);
        TabelaFuncionario.getColumnModel().getColumn(6).setPreferredWidth(200);
    }

    //metodo para carregar os dados do banco na tababela
    public void listar() {
        try {
            Dao_Funcionario d = new Dao_Funcionario();
            ArrayList<Funcionario> objs = d.listarFuncionario();
            DefaultTableModel model = (DefaultTableModel) TabelaFuncionario.getModel();
            model.setNumRows(0);// vai iniciar com 0 linhas
            //percorrer a lista de objetos
            for(Funcionario f: objs){
                model.addRow(new Object[]{
                   f.getCodigo(),f.getNome(),f.getTelefone(),
                   f.getLogin(),f.getSenha(),f.getCodigo_Departamento().getNome(),
                   f.getCodigo_Departamento().getSetor()   
                });
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public CadastroFuncionario() {
        initComponents();
        ajustarTabela();
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtextCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtextNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtextTelefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtextLogin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jpSenha = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jcDepartamento = new javax.swing.JComboBox();
        jbCadastrar = new javax.swing.JButton();
        jBalterar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        textSetor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaFuncionario = new javax.swing.JTable();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(27, 187, 25));

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gestão de Funcionário");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Código:");

        jtextCodigo.setEditable(false);

        jLabel2.setText("Nome:");

        jtextNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextNomeActionPerformed(evt);
            }
        });

        jLabel3.setText("Telefone:");

        jLabel4.setText("Login:");

        jLabel5.setText("Senha:");

        jLabel6.setText("Departamento:");

        jcDepartamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcDepartamentoItemStateChanged(evt);
            }
        });
        jcDepartamento.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jcDepartamentoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jcDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcDepartamentoActionPerformed(evt);
            }
        });

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jBalterar.setText("Alterar");
        jBalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalterarActionPerformed(evt);
            }
        });

        jButton3.setText("Pesquisar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Remover");

        jButton5.setText("Limpar Campos");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        textSetor.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtextLogin)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jpSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcDepartamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtextTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBalterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jtextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jtextTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jpSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtextLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jcDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jbCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBalterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        TabelaFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Telefone", "Login", "Senha", "Departamento", "Setor"
            }
        ));
        TabelaFuncionario.setRowHeight(25);
        TabelaFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaFuncionarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaFuncionario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcDepartamentoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jcDepartamentoAncestorAdded
        try {
            Dao_Departamento dao = new Dao_Departamento();
            ArrayList<Departamento> objs = dao.listarDepartamento();
            jcDepartamento.removeAll();// removo os itens para deixar limpo e não deixa dados duplicados
            jcDepartamento.addItem("Selecione o Departamento");
            for (Departamento d : objs) {
                jcDepartamento.addItem(d);
            }

        } catch (Exception e) {

            e.printStackTrace();
        }
    }//GEN-LAST:event_jcDepartamentoAncestorAdded

    private void jtextNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextNomeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jtextNomeActionPerformed

    private void jcDepartamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcDepartamentoItemStateChanged
        // ele pega o item selecionado da combobox
        try {
            Dao_Departamento dao = new Dao_Departamento();
            Departamento dep = new Departamento();
            dep = (Departamento) jcDepartamento.getSelectedItem();

            ArrayList<Departamento> listas = dao.listarSetor(dep.getCodigo());
            for (Departamento i : listas) {
                textSetor.setText(i.getSetor());
            }
        } catch (Exception e) {

        }

    }//GEN-LAST:event_jcDepartamentoItemStateChanged

    private void jcDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcDepartamentoActionPerformed
        //codigo do action do combobox
        
    }//GEN-LAST:event_jcDepartamentoActionPerformed

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        // botão cadastrar Funcionario 
        try {
            Dao_Funcionario dao = new Dao_Funcionario();
            Funcionario funcionario = new Funcionario();
            funcionario.setNome(jtextNome.getText());
            funcionario.setTelefone(jtextTelefone.getText());
            funcionario.setLogin(jtextLogin.getText());
            funcionario.setSenha(jpSenha.getText());

            Departamento departamento = (Departamento) jcDepartamento.getSelectedItem();
            funcionario.setCodigo_Departamento(departamento);
            dao.cadastrarFuncionario(funcionario);
            listar();
            jtextCodigo.setText("");
            jtextNome.setText("");
            jtextTelefone.setText("");
            jtextLogin.setText("");
            jpSenha.setText("");
            
         
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // botão pesquisar
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // limpar os campos
            jtextCodigo.setText("");
            jtextNome.setText("");
            jtextTelefone.setText("");
            jtextLogin.setText("");
            jpSenha.setText("");
            jcDepartamento.removeAll();
            textSetor.setText("");
            jcDepartamento.removeAll();
            jcDepartamento.setSelectedIndex(0);
           
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jBalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalterarActionPerformed
        // botão alterar funcionario
        try{
        Funcionario funcionario = new Funcionario();
        Dao_Funcionario dao = new Dao_Funcionario();
        Departamento departamento = (Departamento) jcDepartamento.getSelectedItem();
        funcionario.setCodigo(Integer.valueOf(jtextCodigo.getText()));
        funcionario.setCodigo_Departamento(departamento);
        funcionario.setNome(jtextNome.getText());
        funcionario.setLogin(jtextLogin.getText());
        funcionario.setSenha(jpSenha.getText());
        funcionario.setTelefone(jtextTelefone.getText());
       
       // dao.alterarFuncionario(funcionario);
        }catch(Exception e){
        e.printStackTrace();
        }
        
    }//GEN-LAST:event_jBalterarActionPerformed

    private void TabelaFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaFuncionarioMouseClicked
        //pegando o valot atravez do click
        jtextCodigo.setText(TabelaFuncionario.getValueAt
        (TabelaFuncionario.getSelectedRow(),0).toString());
        jtextNome.setText(TabelaFuncionario.getValueAt(
                TabelaFuncionario.getSelectedRow(),1).toString());
        jtextTelefone.setText(TabelaFuncionario.getValueAt(
                TabelaFuncionario.getSelectedRow(),2).toString());
        jtextLogin.setText(TabelaFuncionario.getValueAt(
                TabelaFuncionario.getSelectedRow(),3).toString());
        jpSenha.setText(TabelaFuncionario.getValueAt(
                TabelaFuncionario.getSelectedRow(),4).toString());
        
        //pegar o valor da tabela e jogar na combobox que é um array
        String model = TabelaFuncionario.getValueAt(
                TabelaFuncionario.getSelectedRow(),5).toString();
        for(int i=0; i < jcDepartamento.getItemCount();i++){
            if(jcDepartamento.getItemAt(i).toString().equalsIgnoreCase(model)){
               jcDepartamento.setSelectedIndex(i);
            }
        }
        
        textSetor.setText(TabelaFuncionario.getValueAt(
                TabelaFuncionario.getSelectedRow(),6).toString());
    }//GEN-LAST:event_TabelaFuncionarioMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaFuncionario;
    private javax.swing.JButton jBalterar;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JComboBox jcDepartamento;
    private javax.swing.JPasswordField jpSenha;
    private javax.swing.JTextField jtextCodigo;
    private javax.swing.JTextField jtextLogin;
    private javax.swing.JTextField jtextNome;
    private javax.swing.JTextField jtextTelefone;
    private javax.swing.JTextField textSetor;
    // End of variables declaration//GEN-END:variables
}
