/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.Dao_Departamento;
import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Departamento;

/**
 *
 * @author Miguel
 */
public class CadastroDepartamento extends javax.swing.JInternalFrame {
     
    public void ajustarTabela(){
       TabelaDepartamento.getColumnModel().getColumn(0).setPreferredWidth(50);
       TabelaDepartamento.getColumnModel().getColumn(1).setPreferredWidth(300);
       TabelaDepartamento.getColumnModel().getColumn(2).setPreferredWidth(100);
    }
     public void listar() throws Exception{
        Dao_Departamento dao = new Dao_Departamento();
        ArrayList<Departamento> dps = dao.listarDepartamento();
        ajustarTabela();//metodo que criei para poder ajustar as colunas da tabela.
        //eu crio um Tablemodel e passo o nome databela fazendo um cast para o tableModel
        DefaultTableModel model = (DefaultTableModel)TabelaDepartamento.getModel(); 
        model.setNumRows(0);//digo que vai iniciar com 0 linhas
        
        for(Departamento d: dps){
            model.addRow(new Object[]{
            d.getCodigo(),
            d.getNome(),
            d.getSetor()
            });
        }
        
    }
    public CadastroDepartamento() throws Exception {
        initComponents();
        ajustarTabela();
        this.setMaximizable(true);
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtextNome = new javax.swing.JTextField();
        jtextNomeSetor = new javax.swing.JTextField();
        jbCadastrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaDepartamento = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jtextCodigo = new javax.swing.JTextField();
        jbAlterar = new javax.swing.JButton();
        jbPesquisar = new javax.swing.JButton();
        jbRemover = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Gestão de Departamento");
        setMaximumSize(new java.awt.Dimension(1200, 700));
        setMinimumSize(new java.awt.Dimension(800, 700));

        jPanel2.setBackground(new java.awt.Color(27, 187, 25));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gestão de Departamento");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Nome:");

        jLabel2.setText("Nome Setor:");

        jbCadastrar.setBackground(new java.awt.Color(58, 65, 84));
        jbCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbCadastrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbCadastrarMouseExited(evt);
            }
        });
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        TabelaDepartamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TabelaDepartamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome Departamento", "Setor"
            }
        ));
        TabelaDepartamento.setFocusable(false);
        TabelaDepartamento.setRowHeight(25);
        TabelaDepartamento.setSelectionBackground(new java.awt.Color(153, 153, 153));
        TabelaDepartamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaDepartamentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaDepartamento);

        jLabel4.setText("Código:");

        jtextCodigo.setEditable(false);

        jbAlterar.setBackground(new java.awt.Color(58, 65, 84));
        jbAlterar.setForeground(new java.awt.Color(255, 255, 255));
        jbAlterar.setText("Alterar");
        jbAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbAlterarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbAlterarMouseExited(evt);
            }
        });
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbPesquisar.setBackground(new java.awt.Color(58, 65, 84));
        jbPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbPesquisarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbPesquisarMouseExited(evt);
            }
        });
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jbRemover.setBackground(new java.awt.Color(58, 65, 84));
        jbRemover.setForeground(new java.awt.Color(255, 255, 255));
        jbRemover.setText("Remover");
        jbRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbRemoverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbRemoverMouseExited(evt);
            }
        });
        jbRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoverActionPerformed(evt);
            }
        });

        jbLimpar.setBackground(new java.awt.Color(58, 65, 84));
        jbLimpar.setForeground(new java.awt.Color(255, 255, 255));
        jbLimpar.setText("Limpar campos");
        jbLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbLimparMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbLimparMouseExited(evt);
            }
        });
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtextNome, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtextNomeSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbAlterar)
                            .addComponent(jbCadastrar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbRemover)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jtextNomeSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbLimpar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 839, 526);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        // cadastrar Departamento
        Dao_Departamento dao = new Dao_Departamento();
        Departamento departamento = new Departamento();
      
        if(!jtextNome.getText().trim().equals("") && !jtextNomeSetor.getText().trim().equals("")){
         String nome = jtextNome.getText();
         String setor = jtextNomeSetor.getText();      
         departamento.setNome(nome);
         departamento.setSetor(setor);
            try {
                dao.cadastrarDepartamento(departamento);
              //  jtextCodigo.
                listar();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            
        jtextNome.setText("");
        jtextNomeSetor.setText("");
        
        }else{
         JOptionPane.showMessageDialog(null, "Todos os campos precisam ser preenchidos");
         jtextNome.setText("");
         jtextNomeSetor.setText("");
        }
        
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbCadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCadastrarMouseEntered
        //evento quando passar o mouse por cima.
        jbCadastrar.setBackground(new Color(235,235,235));
        jbCadastrar.setForeground(new Color(58,65,84));
    }//GEN-LAST:event_jbCadastrarMouseEntered

    private void jbCadastrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCadastrarMouseExited
        // evento quando o mouse sair do botão.
        jbCadastrar.setBackground(new Color(58,65,84));
        jbCadastrar.setForeground(new Color(235,235,235));
    }//GEN-LAST:event_jbCadastrarMouseExited

    private void TabelaDepartamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaDepartamentoMouseClicked
        /* Evento para quando clicar na linha da tabela subir os valores para meus
        campos acima.
        
        TabelaDepartamento.getValueAt(linha,coluna); ele responsavel por pegar valores de linha e colunas
        TabelaDepartamento.getSelectedRow(); este metodo pega a linha selecionada.
        */
        jtextCodigo.setText(TabelaDepartamento.getValueAt
        (TabelaDepartamento.getSelectedRow(),0).toString());
        
        jtextNome.setText(TabelaDepartamento.getValueAt
        (TabelaDepartamento.getSelectedRow(),1).toString());
        
        jtextNomeSetor.setText(TabelaDepartamento.getValueAt
        (TabelaDepartamento.getSelectedRow(), 2).toString());
        
    }//GEN-LAST:event_TabelaDepartamentoMouseClicked

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        if(!jtextNome.getText().trim().equals("") && 
                !jtextNomeSetor.getText().trim().equals("")){
        //atualizar o departamento
        Dao_Departamento dao = new Dao_Departamento();
        Departamento departamento = new Departamento();
        departamento.setCodigo(Integer.valueOf(jtextCodigo.getText()));
        departamento.setNome(jtextNome.getText());
        departamento.setSetor(jtextNomeSetor.getText());
        try{
        dao.alterarDepartamento(departamento);
        listar();
        jtextCodigo.setText("");
        jtextNome.setText("");
        jtextNomeSetor.setText("");
        }catch(Exception e){
        e.printStackTrace();
       }
      }else{
           JOptionPane.showMessageDialog(null, "campos em branco não podem ser atualizados");
        }
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbAlterarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAlterarMouseEntered
        //evento quando passar o mouse por cima.
        jbAlterar.setBackground(new Color(235,235,235));
        jbAlterar.setForeground(new Color(58,65,84));
    }//GEN-LAST:event_jbAlterarMouseEntered

    private void jbAlterarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAlterarMouseExited
        //evento quando passar o mouse por cima.
        jbAlterar.setBackground(new Color(58,65,84));
        jbAlterar.setForeground(new Color(235,235,235));
    }//GEN-LAST:event_jbAlterarMouseExited

    private void jbRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoverActionPerformed
        // remover departamento
        Dao_Departamento dao = new Dao_Departamento();
        Departamento departamento = new Departamento();
        try{
         if(!jtextNome.getText().trim().equals("") && 
                !jtextNomeSetor.getText().trim().equals("")){
          departamento.setCodigo(Integer.valueOf(jtextCodigo.getText()));
          dao.removerDepartamento(departamento);
          listar();
         }else{
         JOptionPane.showMessageDialog(null, "campos vazios não podem ser excluidos!");
         }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jbRemoverActionPerformed

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        // pesquisar pelo nome do departamento
        String nome = jtextNome.getText();
        String setor = jtextNomeSetor.getText();
        ArrayList<Departamento> departamentos = new ArrayList<Departamento>();
        if(!nome.trim().equals("") || 
                !setor.trim().equals("")){
            try{
            Dao_Departamento dao = new Dao_Departamento();
            Departamento departamento = new Departamento();
            departamento.setNome(nome);
            departamento.setSetor(setor);
            departamentos = dao.pesquisarDepartamento(departamento);
            
            DefaultTableModel model = (DefaultTableModel)TabelaDepartamento.getModel();
            model.setNumRows(0);
            for(Departamento d:departamentos){
                model.addRow(new Object[]{
                d.getCodigo(),
                d.getNome(),
                d.getSetor()
                });
            }
            }catch(Exception e){
                e.printStackTrace();
            }
        
        }else{
          JOptionPane.showMessageDialog(null, "campos vazio não pode ser pesquisado!");
        }
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        // limpar os campos da tabela.
        jtextCodigo.setText("");
        jtextNome.setText("");
        jtextNomeSetor.setText("");
        try{
        listar();
        }catch(Exception e){
           e.printStackTrace();
        }
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbPesquisarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPesquisarMouseEntered
        // TODO add your handling code here:
        jbPesquisar.setBackground(new Color(235,235,235));
        jbPesquisar.setForeground(new Color(58,65,84));
    }//GEN-LAST:event_jbPesquisarMouseEntered

    private void jbPesquisarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPesquisarMouseExited
        // TODO add your handling code here:
        jbPesquisar.setBackground(new Color(58,65,84));
        jbPesquisar.setForeground(new Color(235,235,235));
    }//GEN-LAST:event_jbPesquisarMouseExited

    private void jbRemoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRemoverMouseEntered
        // TODO add your handling code here:
        jbRemover.setBackground(new Color(235,235,235));
        jbRemover.setForeground(new Color(58,65,84));
    }//GEN-LAST:event_jbRemoverMouseEntered

    private void jbRemoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRemoverMouseExited
        // TODO add your handling code here:
        jbRemover.setBackground(new Color(58,65,84));
        jbRemover.setForeground(new Color(235,235,235));
    }//GEN-LAST:event_jbRemoverMouseExited

    private void jbLimparMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbLimparMouseEntered
        // TODO add your handling code here:
        jbLimpar.setBackground(new Color(235,235,235));
        jbLimpar.setForeground(new Color(58,65,84));
    }//GEN-LAST:event_jbLimparMouseEntered

    private void jbLimparMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbLimparMouseExited
        // TODO add your handling code here:
        jbLimpar.setBackground(new Color(58,65,84));
        jbLimpar.setForeground(new Color(235,235,235));
    }//GEN-LAST:event_jbLimparMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaDepartamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbRemover;
    private javax.swing.JTextField jtextCodigo;
    private javax.swing.JTextField jtextNome;
    private javax.swing.JTextField jtextNomeSetor;
    // End of variables declaration//GEN-END:variables
}
